spring.application.name=PawsStore

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0411\u0414
spring.datasource.url=jdbc:postgresql://localhost:5436/pawsstore
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# \u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0441\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0439
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.messages.fallback-to-system-locale=false

# \u041E\u0442\u043A\u043B\u044E\u0447\u0430\u0435\u043C \u043A\u044D\u0448 \u0434\u043B\u044F \u0440\u0430\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0438
spring.thymeleaf.cache=false